[project]
name = "FirstDjangoModel"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django==4.2.4",
    "psycopg2-binary==2.9.7",
    "python-dotenv>=1.1.1",
]
